# -*- coding: utf-8 -*-

from PySide2.QtCore import *
from PySide2.QtWidgets import *
from PySide2.QtGui import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(237, 369)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fill_btn = QPushButton(self.centralwidget)
        self.fill_btn.setObjectName("fill_btn")
        self.horizontalLayout.addWidget(self.fill_btn)
        self.clear_btn = QPushButton(self.centralwidget)
        self.clear_btn.setMinimumSize(QSize(40, 0))
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)
        self.image_lb = QLabel(self.centralwidget)
        self.image_lb.setObjectName("image_lb")
        self.horizontalLayout.addWidget(self.image_lb)
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.combo_cbb = QComboBox(self.centralwidget)
        self.combo_cbb.setObjectName("combo_cbb")
        self.verticalLayout.addWidget(self.combo_cbb)
        self.list_lwd = QListWidget(self.centralwidget)
        self.list_lwd.setObjectName("list_lwd")
        self.verticalLayout.addWidget(self.list_lwd)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.label = QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setGeometry(QRect(0, 0, 237, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.fill_act = QAction(MainWindow)
        self.fill_act.setObjectName("fill_act")
        self.clear_act = QAction(MainWindow)
        self.clear_act.setObjectName("clear_act")
        self.open_act = QAction(MainWindow)
        self.open_act.setObjectName("open_act")
        self.save_act = QAction(MainWindow)
        self.save_act.setObjectName("save_act")
        self.exit_act = QAction(MainWindow)
        self.exit_act.setObjectName("exit_act")
        self.toolBar.addAction(self.fill_act)
        self.toolBar.addAction(self.clear_act)
        self.menuFile.addAction(self.open_act)
        self.menuFile.addAction(self.save_act)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.exit_act)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QApplication.translate("MainWindow", "MainWindow", None))
        self.fill_btn.setText(QApplication.translate("MainWindow", "Fill", None))
        self.clear_btn.setText(
            QApplication.translate("MainWindow", "Clear", None))
        self.image_lb.setText(
            QApplication.translate("MainWindow", "TextLabel", None))
        self.toolBar.setWindowTitle(
            QApplication.translate("MainWindow", "toolBar", None))
        self.menuFile.setTitle(QApplication.translate("MainWindow", "File", None))
        self.fill_act.setText(QApplication.translate("MainWindow", "Fill", None))
        self.clear_act.setText(
            QApplication.translate("MainWindow", "Clear", None))
        self.open_act.setText(QApplication.translate("MainWindow", "Open", None))
        self.save_act.setText(QApplication.translate("MainWindow", "Save", None))
        self.exit_act.setText(QApplication.translate("MainWindow", "Exit", None))
